# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
